const express = require('express');
const { protect, requireRoles, requireUser, requireDriver } = require('../middleware/auth');
const c = require('../controllers/communicationController');
const conversations = express.Router();
conversations.use(protect, requireRoles('user', 'driver'));
conversations.get('/presets', c.presets);
conversations.get('/audience', c.audience);
conversations.get('/', c.listThreads);
conversations.post('/', c.createThread);
conversations.get('/:id/messages', c.messages);
conversations.post('/:id/messages', c.send);
conversations.put('/:id/read', c.read);
const absences = express.Router();
absences.use(protect, requireRoles('user', 'driver'));
absences.get('/', c.listAbsences);
absences.post('/', requireUser, c.report);
absences.post('/:id/cancel', requireUser, c.cancel);
absences.post('/:id/acknowledge', requireDriver, c.acknowledge);
const driver = express.Router();
driver.use(protect, requireDriver);
driver.get('/riders', c.audience);
driver.get('/riders/:riderId', c.riderDetail);
driver.get('/riders/:riderId/avatar', c.riderAvatar);
driver.get('/absences', c.listAbsences);
driver.get('/announcements', c.announcements);
driver.post('/announcements', c.announce);
driver.get('/announcements/:id', c.announcement);
driver.post('/announcements/:id/retry', c.retryAnnouncement);
module.exports = { conversations, absences, driver };
